pipeline {
    agent any

    environment {
        Angular_PATH = 'C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\angular-build\\angular-project\\sample-angular-17-project\\'
        Docker_PATH = 'C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\angular-build\\angular-project\\docker\\'
    }

    tools {
        nodejs 'nodejs-lts'
    }

    stages {
        stage("Pulling code from Github") {
            steps {
                script {
                    deleteDir()
                    bat "git clone https://github.com/sharsh15/angular-project.git"
                }
                echo "Cloned repository successfully."
            }
        }

        stage("Installing dependencies") {
            steps {
                bat """
                    cd ${env.Angular_PATH}
                    npm install
                    npm --version
                """
                echo "Dependencies installed"
            }
        }

        stage("Building Angular App") {
            steps {
                 bat """
                    cd ${env.Angular_PATH} && npx ng build
                """
                echo "Angular app successfully completed"
            }
        }

        stage("Dockerizing the angular app") {
            steps {
                bat """
                    cd ${env.Docker_PATH}
                    docker build -t angular-app .
                """
                echo "Docker image built"
            }
        }
    }
}