pipeline {
    agent any

    parameters {
        string(name: 'IP_address', defaultValue: 'IP-address', description: 'Enter the public IP address of the EC2 instance')
    }

    environment {
      //  IMAGE_NAME_PREFIX = 'harsh1510/real-world-project:'
        AWS_PAIR_KEY_PATH = 'D:\\Trycath-Devops\\AWS\\Devopskeypair.pem'
    }

    stages {
        stage("Deploy App on AWS EC2 Server") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials',
                                                  usernameVariable: 'DOCKERHUB_USER',
                                                  passwordVariable: 'DOCKERHUB_PASS')]) {
                    bat """
                        ssh -i ${env.AWS_PAIR_KEY_PATH} -o StrictHostKeyChecking=no ubuntu@${params.IP_address} ^
                        "echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin && \
                        sudo docker pull harsh1510/angular-app:version1 && \
                        sudo docker stop harsh1510/angular-app && \
                        sudo docker rm -f harsh1510/angular-app || true && \
                        sudo docker run -d --name angular-app -p 4200:80 harsh1510/angular-app:version1 && \
                        sudo docker ps -a"
                    """
                }
            }
        }
    }
}